---
title: "Geo_models"
author: "ModaE"
output: 
  html_document: 
---

### Datos

| ID | Datos | Fuente | Estado | Link |
|----|----|----|----|----|
| data1 | Alojamientos Turisticos por municipio | CAIB | raw | [Link](https://www.caib.es/sites/estadistiquesdelturisme/ca/allotjaments_turastics/) |
| data2 | IPH diario por isla | IBESTAT | raw | [Link](https://ibestat.es/edatos/apps/statistical-visualizer/visualizer/collection.html?resourceType=collection&agencyId=IBESTAT&resourceId=000011A_000001) |
| data3 | Turismo interno y receptor por municipio de destino | INE | raw | [Link](https://www.ine.es/experimental/turismo_moviles/experimental_turismo_moviles.htm) |
| data4 | Población censada por municipio por sexo | INE | raw | [Link](https://www.ine.es/pob_xls/pobmun.zip) |
| \- | Movimientos turísticos en frontera | FRONTUR | wip | [Link](https://ibestat.es/estadistica/economia/turismo/flujo-de-turistas-frontur/) |
| data5 | Ocupación de Calvià, Capdepera, Palma y St Llorenç | INE | raw | [Link](https://ine.es/jaxiT3/Tabla.htm?t=2076) |
|  | Turistas con destino principal las Baleares | IBESTAT | wip | [Link](https://ibestat.es/edatos/apps/statistical-visualizer/visualizer/data.html?resourceType=dataset&agencyId=IBESTAT&resourceId=000058A_000002&version=~latest#visualization/table) |





# Desagregación espacial del turismo en Mallorca (Prototipo 2)

## Visualización interactiva
**[Gráfica de resultados](https://ricuib.github.io/M02sandbox/Mallorca.html)**

Esta visualización muestra una desagregación espacial del turismo en Mallorca a nivel municipal, combinando: data1, data2 y data3

La gráfica permite explorar la evolución temporal del turismo y comparar patrones entre municipios mediante una visualización interactiva.


El enfoque se basa en la metodología de desagregación espacial propuesta en: [Spatial disaggregation of time series](https://arxiv.org/abs/2509.04065)

Tobar, A., Mir, A., Alberich, R., Mosquera, I. G., Miró, M., & Cruz, N. A. (2025). Spatial disaggregation of time series. arXiv preprint arXiv:2509.04065.
